### ISSUE TITLE
Not sure what to pull from test data

### ISSUE THREAD

**Issue by charitsharma** [rseniuta/elasticsearch-nest-webapi-angularjs#2]
Hi, I am trying to get the sample data but not sure what to pull for posts.xml file. can you please help.

**Comment by rseniuta** [comment]
Hi, follow [docs](https://github.com/rseniuta/elasticsearch-nest-webapi-angularjs#download-test-data).
Choose archive you want, extract it and copy posts.xml to data folder.

**Comment by charitsharma** [comment]
Thanks I am able to pull posts.xml, Now I want to know when you say data folder, do I need to create data folder under \elasticsearch-nest-webapi-angularjs\data or need to push posts.xml to elasticsearch-2.4.1\data location where I installed elastic search. Also I have question about index. How to index after including posts.xml on the right place. Do I need to run elasticsearch before indexing and how to create index for this posts.xml file.
This is too much to ask but I am new to elastic search and want to understand auto complete functionality with this example. and I would appreciate your help. Thanks.

**Comment by charitsharma** [comment]
Find the answers by myself. Thanks.
