### ISSUE TITLE
xml file

### ISSUE THREAD

**Issue by windson** [rseniuta/elasticsearch-nest-webapi-angularjs#3]
Can you please tell which archive contains posts.xml file ?
I tried to see there are lots of archives on https://archive.org/download/stackexchange
It would be great help if you upload the xml file directly. Thanks

**Comment by rseniuta** [comment]
Pick one that is interesting to you, for example: [chess.stackexchange.com](https://archive.org/download/stackexchange/chess.stackexchange.com.7z)
download, unzip and then you will find Posts.xml
